import { FetchedAccount } from './account'
import { FetchedCategory } from './category'
import { FetchedTransaction } from './transaction'

let categories: FetchedCategory[] = [
	{ id: 'cat1', name: 'Groceries', order_position: 1 },
	{ id: 'cat2', name: 'Utilities', order_position: 2 },
	{ id: 'cat3', name: 'Entertainment', order_position: 3 },
	{ id: 'cat4', name: 'Transport', order_position: 4 },
	{ id: 'cat5', name: 'Healthcare', order_position: 5 },
	{ id: 'cat6', name: 'Miscellaneous', order_position: 6 },
]

let accounts: FetchedAccount[] = [
	{ id: 'acc1', name: 'Checking', order_position: 1, starting_amount: 1000 },
	{ id: 'acc2', name: 'Savings', order_position: 2, starting_amount: 5000 },
	{ id: 'acc3', name: 'Credit Card', order_position: 3, starting_amount: -200 },
]

let transactions: FetchedTransaction[] = [
	{
		id: 'txn1',
		date: '2025-01-01',
		name: 'Weekly Groceries',
		order_position: 1,
		items: [
			{
				id: 'item1',
				account_id: 'acc1',
				category_id: 'cat1',
				name: 'Bread',
				amount: 3,
				order_position: 1,
			},
			{
				id: 'item2',
				account_id: 'acc1',
				category_id: 'cat1',
				name: 'Eggs',
				amount: 5,
				order_position: 2,
			},
			{
				id: 'item3',
				account_id: 'acc1',
				category_id: 'cat1',
				name: 'Milk',
				amount: 4,
				order_position: 3,
			},
		],
	},
	{
		id: 'txn2',
		date: '2025-01-01',
		name: 'Movie Night',
		order_position: 2,
		items: [
			{
				id: 'item4',
				account_id: 'acc1',
				category_id: 'cat3',
				name: 'Tickets',
				amount: 15,
				order_position: 1,
			},
			{
				id: 'item5',
				account_id: 'acc1',
				category_id: 'cat3',
				name: 'Popcorn',
				amount: 7,
				order_position: 2,
			},
			{
				id: 'item6',
				account_id: 'acc1',
				category_id: 'cat3',
				name: 'Soda',
				amount: 5,
				order_position: 3,
			},
		],
	},
	{
		id: 'txn3',
		date: '2025-01-01',
		name: 'Pharmacy Visit',
		order_position: 3,
		items: [
			{
				id: 'item7',
				account_id: 'acc1',
				category_id: 'cat5',
				name: 'Painkillers',
				amount: 12,
				order_position: 1,
			},
			{
				id: 'item8',
				account_id: 'acc1',
				category_id: 'cat5',
				name: 'Vitamins',
				amount: 8,
				order_position: 2,
			},
			{
				id: 'item9',
				account_id: 'acc1',
				category_id: 'cat5',
				name: 'Bandages',
				amount: 5,
				order_position: 3,
			},
		],
	},
	{
		id: 'txn4',
		date: '2025-01-02',
		name: 'Electricity Bill',
		order_position: 4,
		items: [
			{
				id: 'item10',
				account_id: 'acc1',
				category_id: 'cat2',
				name: 'Power Usage',
				amount: 100,
				order_position: 1,
			},
			{
				id: 'item11',
				account_id: 'acc1',
				category_id: 'cat2',
				name: 'Meter Fee',
				amount: 10,
				order_position: 2,
			},
			{
				id: 'item12',
				account_id: 'acc1',
				category_id: 'cat2',
				name: 'Service Charge',
				amount: 5,
				order_position: 3,
			},
		],
	},
	{
		id: 'txn5',
		date: '2025-01-02',
		name: 'Gas Refill',
		order_position: 5,
		items: [
			{
				id: 'item13',
				account_id: 'acc1',
				category_id: 'cat4',
				name: 'Regular Gas',
				amount: 50,
				order_position: 1,
			},
			{
				id: 'item14',
				account_id: 'acc1',
				category_id: 'cat4',
				name: 'Snacks',
				amount: 8,
				order_position: 2,
			},
			{
				id: 'item15',
				account_id: 'acc1',
				category_id: 'cat4',
				name: 'Car Wash',
				amount: 12,
				order_position: 3,
			},
		],
	},
	{
		id: 'txn6',
		date: '2025-01-03',
		name: 'Lunch Out',
		order_position: 6,
		items: [
			{
				id: 'item16',
				account_id: 'acc1',
				category_id: 'cat3',
				name: 'Pasta',
				amount: 18,
				order_position: 1,
			},
			{
				id: 'item17',
				account_id: 'acc1',
				category_id: 'cat3',
				name: 'Salad',
				amount: 10,
				order_position: 2,
			},
			{
				id: 'item18',
				account_id: 'acc1',
				category_id: 'cat3',
				name: 'Dessert',
				amount: 8,
				order_position: 3,
			},
		],
	},
	{
		id: 'txn7',
		date: '2025-01-03',
		name: 'Online Shopping',
		order_position: 7,
		items: [
			{
				id: 'item19',
				account_id: 'acc1',
				category_id: 'cat6',
				name: 'Books',
				amount: 25,
				order_position: 1,
			},
			{
				id: 'item20',
				account_id: 'acc1',
				category_id: 'cat6',
				name: 'Clothing',
				amount: 40,
				order_position: 2,
			},
			{
				id: 'item21',
				account_id: 'acc1',
				category_id: 'cat6',
				name: 'Accessories',
				amount: 15,
				order_position: 3,
			},
		],
	},
	{
		id: 'txn8',
		date: '2025-01-03',
		name: 'Coffee Shop',
		order_position: 8,
		items: [
			{
				id: 'item22',
				account_id: 'acc1',
				category_id: 'cat3',
				name: 'Latte',
				amount: 5,
				order_position: 1,
			},
			{
				id: 'item23',
				account_id: 'acc1',
				category_id: 'cat3',
				name: 'Muffin',
				amount: 4,
				order_position: 2,
			},
			{
				id: 'item24',
				account_id: 'acc1',
				category_id: 'cat3',
				name: 'Sandwich',
				amount: 7,
				order_position: 3,
			},
		],
	},
	{
		id: 'txn9',
		date: '2025-01-04',
		name: 'Gym Membership',
		order_position: 9,
		items: [
			{
				id: 'item25',
				account_id: 'acc1',
				category_id: 'cat5',
				name: 'Monthly Fee',
				amount: 50,
				order_position: 1,
			},
			{
				id: 'item26',
				account_id: 'acc1',
				category_id: 'cat5',
				name: 'Trainer Tip',
				amount: 20,
				order_position: 2,
			},
			{
				id: 'item27',
				account_id: 'acc1',
				category_id: 'cat5',
				name: 'Equipment Rental',
				amount: 10,
				order_position: 3,
			},
		],
	},
	{
		id: 'txn10',
		date: '2025-01-04',
		name: 'Weekend Groceries',
		order_position: 10,
		items: [
			{
				id: 'item28',
				account_id: 'acc1',
				category_id: 'cat1',
				name: 'Fruits',
				amount: 15,
				order_position: 1,
			},
			{
				id: 'item29',
				account_id: 'acc1',
				category_id: 'cat1',
				name: 'Vegetables',
				amount: 20,
				order_position: 2,
			},
			{
				id: 'item30',
				account_id: 'acc1',
				category_id: 'cat1',
				name: 'Snacks',
				amount: 10,
				order_position: 3,
			},
		],
	},
]

const dummyData = { categories, accounts, transactions }
const exprt = { dummyData }
export default exprt
