export { ReactComponent as AboutMeIcon } from './navbar_icons/about-me.svg'
export { ReactComponent as SkillsIcon } from './navbar_icons/skills.svg'
export { ReactComponent as ProjectsIcon } from './navbar_icons/projects.svg'
export { ReactComponent as ExperienceIcon } from './navbar_icons/experience.svg'
export { ReactComponent as ContactInfoIcon } from './navbar_icons/contact-info.svg'
