export { ReactComponent as AboutMeIcon } from './navbar_icons/about-me.svg'
export { ReactComponent as SkillsIcon } from './navbar_icons/skills.svg'
export { ReactComponent as ProjectsIcon } from './navbar_icons/projects.svg'
export { ReactComponent as ExperienceIcon } from './navbar_icons/experience.svg'
export { ReactComponent as ContactInfoIcon } from './navbar_icons/contact-info.svg'

export { ReactComponent as CSSIcon } from './skills_icons/css.svg'
export { ReactComponent as HTMLIcon } from './skills_icons/html.svg'
export { ReactComponent as JavaScriptIcon } from './skills_icons/javascript.svg'
export { ReactComponent as ReactRouterIcon } from './skills_icons/react_router.svg'
export { ReactComponent as ReactIcon } from './skills_icons/react.svg'
export { ReactComponent as SassIcon } from './skills_icons/sass.svg'
export { ReactComponent as TypeScriptIcon } from './skills_icons/typescript.svg'
