export { AboutMe } from './AboutMe'
export { Skills } from './Skills/Skills'
export { Projects } from './Projects/Projects'
export { Experience } from './Experience'
export { ContactInfo } from './ContactInfo'
