export { AboutMe } from './AboutMe/AboutMe'
export { Skills } from './Skills/Skills'
export { Projects } from './Projects/Projects'
export { Experience } from './Experience/Experience'
export { ContactInfo } from './ContactInfo/ContactInfo'
